# Generated by Django 3.2.6 on 2024-12-29 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_truck_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Truck',
        ),
    ]
