# Generated by Django 3.2.6 on 2025-01-07 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20250107_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_city', models.CharField(max_length=255)),
                ('arrival_city', models.CharField(max_length=255)),
                ('departure_date', models.DateTimeField()),
                ('arrival_date', models.DateTimeField()),
                ('phone_number', models.CharField(max_length=20)),
                ('tonnage', models.IntegerField()),
                ('loaded_trip', models.BooleanField(default=False)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.truck')),
            ],
            options={
                'db_table': 'delivery',
            },
        ),
    ]
