# Generated by Django 3.2.6 on 2025-01-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='arrival_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='departure_date',
            field=models.DateField(),
        ),
    ]
