# Generated by Django 3.2.6 on 2025-01-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20250115_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='arrival_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='departure_date',
            field=models.DateTimeField(),
        ),
    ]
