# Generated by Django 3.2.6 on 2025-01-23 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20250123_1955'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='delivery',
            table='deliverys',
        ),
    ]
