# Generated by Django 3.2.6 on 2025-01-23 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_delivery_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='delivery',
            table='delivery',
        ),
    ]
