# Generated by Django 3.2.6 on 2025-02-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delay',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
